name: nmoneys build

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      VERBOSITY: q
      CONFIGURATION: Release
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.406
      #- name: Info
      #  run: dotnet --info
      - name: Restore
        shell: pwsh
        run: ./build.ps1 -task Restore -verbosity "${{ env.VERBOSITY }}" -configuration "${{ env.CONFIGURATION }}"
      - name: Compile
        shell: pwsh
        run: ./build.ps1 -task Compile -verbosity "${{ env.VERBOSITY }}" -configuration "${{ env.CONFIGURATION }}"
      - name: Test
        shell: pwsh
        run: ./build.ps1 -task Test -verbosity "${{ env.VERBOSITY }}" -configuration "${{ env.CONFIGURATION }}"
      - name: Pack
        shell: pwsh
        run: ./build.ps1 -task Pack -verbosity "${{ env.VERBOSITY }}" -configuration "${{ env.CONFIGURATION }}"
      - name: Copy-Artifacts
        shell: pwsh
        run: ./build.ps1 -task CopyArtifacts -verbosity "${{ env.VERBOSITY }}" -configuration "${{ env.CONFIGURATION }}"

      - name: Test Reporter
        if: ${{ !env.ACT }}
        uses: dorny/test-reporter@v1.9.1
        with:
          name: Test Report
          path: "./release/TestResults/NMoneys.Tests.xml"
          reporter: dotnet-nunit
          fail-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: tests-results
          path: |
            ./release/TestResults/*.xml

      - name: Upload bin
        uses: actions/upload-artifact@v4
        with:
          name: bin
          path: |
            ./release/*.xml
            ./release/*.pdb
            ./release/*.dll

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ./release/*.nupkg

      - name: Upload Codecov coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./release/TestResults/NMoneys.Tests.cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Upload Coveralls coverage
        uses: coverallsapp/github-action@v2
        with:
          files: ./release/TestResults/NMoneys.Tests.cobertura.xml
          format: cobertura
